apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopops-prod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayush-g/shopops.git
    targetRevision: main
    path: deploy/gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
